package com.qetyspace.quetye_shop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Flower implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Flower() {
    }




}